- name: PMD for Java
  # You may pin to the exact commit or the version.
  # uses: kemsakurai/action-pmd@c6962084feb28d46b1859e9552e5e2f6a96aef73
  uses: kemsakurai/action-pmd@v0.0.3
  with:
    # GITHUB_TOKEN
    # github_token: # optional, default is ${{ github.token }}
    # Working directory relative to the root directory.
    # workdir: # optional, default is .
    # Report level for reviewdog [info,warning,error]
    # level: # optional, default is error
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
    # reporter: # optional, default is github-pr-check
    # Filtering mode for the reviewdog command [added,diff_context,file,nofilter].Default is added.

    # filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false] Default is `false`.

    # fail_on_error: # optional, default is false
    # Tool name to use for reviewdog reporter
    #tool_name: # optional, default is pmd
    # Additional reviewdog flags
    # reviewdog_flags: # optional, default is 
    # Specify the directory where the sources to be analyzed are stored. Default is `src/main/java`.
    
    src_path: server-code-1/AppUserList/src/main/java
    
    # Specify the path of the PMD rule set. Default is `rulesets/java/quickstart.xml`.
    # rulesets_path: # optional, default is rulesets/java/quickstart.xml
