name: pmd-for-java-with-sarif
run-name: ${{ github.actor }} is learning PMD For java, with SARIF File
on: [push]
jobs:
  pmd-for-java-job:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      # actions: read
      # contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          version: '6.40.0'
          sourcePath: 'server-code-1/AppUserList/src/main/java'    
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: pmd-report.sarif
            # category: my-analysis-tool
